name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    
jobs:
  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: |
          cd Platform.Data.Triplets.Kernel/
          make
          ./run.sh 
      - name: Publish
        if: github.event_name == 'push'
        run: |
          export TARGET_PLATFORM="linux-x64"
          export TARGET_PLATFORM_PREFIX="lib"
          export TARGET_PLATFORM_SUFFIX=".so"
          export TRAVIS_REPO_NAME="Data.Triplets.Kernel"
          export SOURCE_BRANCH="master"
          bash ./publish-binaries.sh
      
  buildWindow:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: |
          cd Platform.Data.Triplets.Kernel/
          ls
          mingw32-make
          ./test 
      - name: Publish
        if: github.event_name == 'push'
        run: |
          export TARGET_PLATFORM="win-x64"
          export TARGET_PLATFORM_PREFIX=""
          export TARGET_PLATFORM_SUFFIX=".dll"
          export TRAVIS_REPO_NAME="Data.Triplets.Kernel"
          export SOURCE_BRANCH="master"
          ./publish-binaries.sh
        shell: bash

  buildMacOs:
    runs-on: macos-latest   
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: |
          cd Platform.Data.Triplets.Kernel/
          ls
          make
          ./run.sh       
      - name: Publish
        if: github.event_name == 'push'
        run: |
          export TARGET_PLATFORM="osx-x64"
          export TARGET_PLATFORM_PREFIX="lib"
          export TARGET_PLATFORM_SUFFIX=".dylib"
          export TRAVIS_REPO_NAME="Data.Triplets.Kernel"
          export SOURCE_BRANCH="master"
          bash ./publish-binaries.sh


